{{- if .Values.extraObjects }}
{{- range .Values.extraObjects }}
---
apiVersion: {{ .apiVersion }}
kind: {{ .kind }}
metadata:
  {{- with .metadata }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
